apiVersion: v1
kind: Service
metadata:
  name: iperf-np
spec:
  type: NodePort
  ports:
  - name: tcp-cport
    port:       30000  # Port exposed within the cluster
    targetPort: 30000  # Port on the pods
    nodePort:   30000  # Port accessible externally on each node
    protocol:   TCP
  - name: tcp-dport  
    port:       30001  
    targetPort: 30001  
    nodePort:   30001 
    protocol:   TCP
  - name: udp-cport
    port:       30000  # Port exposed within the cluster
    targetPort: 30000  # Port on the pods
    nodePort:   30000  # Port accessible externally on each node
    protocol:   UDP
  - name: udo-dport  
    port:       30001  
    targetPort: 30001  
    nodePort:   30001 
    protocol:   UDP
  selector:
    app: iperf-app    # Select pods with this label
