apiVersion: v1
kind: Pod
metadata:
  name: uperf-app
  labels:
      app: uperf-app
spec:
  nodeSelector: {"kubernetes.io/hostname": "sno-h07"}
  containers:
  - name: uperf
    image: quay.io/hnhan/ocp-tools:uperf-dash-B
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    securityContext:
      privileged: true

